let ele = document.querySelector('p')
console.log(ele.className)
ele.classList.add("six")
ele.classList.remove("six")
ele.classList.toggle('six')
ele.classList.toggle('six')
console.log(ele)

let q1 = ele.getAttribute('id')
console.log(q1)
ele.setAttribute('id',"nine")
console.log(ele)
ele.setAttribute('data-cy',"username")
ele.removeAttribute('id')
console.log(ele)